# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shulley <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/05/22 11:34:30 by shulley           #+#    #+#              #
#    Updated: 2017/05/22 12:46:40 by shulley          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = phonebook

SRC = Phonebook.cpp			\
	  init_phonebook.cpp   \
	searchcontacts.cpp	\
	  main.cpp

all:
	g++ -o $(NAME) $(SRC)

clean: 
	rm $(NAME)

re:
	clean all

