#!/usr/bin/expect -f

spawn ssh 172.31.0.203

expect "password: "
send "vagrant\r"
expect "$ "
send "sudo apt-get install libopenscap8\r"
expect "$ "
send "git clone https://github.com/GovReady/ubuntu-scap.git\r"
expect "$ "
send "cd ubuntu-scap\r"
expect "$ "
send "./run_tests.sh\r"
expect "$ "
send "lynx report.html\r"
expect "$ "
